In [1]:
import pandas as pd

f_mdef_url = r"C:\Users\Drakharys\Desktop\JustLearning\MUSIC\subject-info_definitions.csv"

f_def = pd.read_csv(f_mdef_url, sep=';', encoding='latin1') # El archivo est√±a codificado como latin1, algun excel antiguo

f_def.head()

,Variable,Column,Definition,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NYHA class,M,New York Heart Association classs,NaN,NaN,NaN,NaN
1,ALT o GPT (IU/L),AD,Alanine Aminotransferase or Glutamic Pyruvic T...,NaN,NaN,NaN,NaN
2,AST o GOT (IU/L),AE,Aspartate Aminotransferase or Glutamyl oxaloac...,NaN,NaN,NaN,NaN
3,HDL (mmol/L),AL,High-density lipoprotein cholesterol,NaN,NaN,NaN,NaN
4,LDL (mmol/L),AN,Low Density Lipoprotein Cholesterol,NaN,NaN,NaN,NaN

In [2]:
# Me cargo las columnas originales innecesarias
f_def = f_def.drop(columns=['Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6'])

f_def.head(10)

          Variable  Column                                         Definition
0        NYHA class      M                  New York Heart Association classs
1  ALT o GPT (IU/L)     AD  Alanine Aminotransferase or Glutamic Pyruvic T...
2  AST o GOT (IU/L)     AE  Aspartate Aminotransferase or Glutamyl oxaloac...
3      HDL (mmol/L)     AL               High-density lipoprotein cholesterol
4      LDL (mmol/L)     AN                Low Density Lipoprotein Cholesterol
5    Pro-BNP (ng/L)     AP                     pro b-type natriuretic peptide
6        T3 (pg/dL)     AR                                   Triiodothyronine
7         T4 (ng/L)     AS                                          Thyroxine
8       TSH (mIU/L)     AU                        Thyroid Stimulating Hormone
9          LVEF (%)     BB                Left Ventricular Ejection Fraction

In [3]:
# Guardo en un nuevo archivo
output_path = r"C:\Users\Drakharys\Desktop\JustLearning\MUSIC\subject-info_def.csv"
f_def.to_csv(output_path, index=False, sep=';', encoding='utf-8')

print(f"Archivo guardado en: {output_path}")

Archivo guardado en: C:\Users\Drakharys\Desktop\JustLearning\MUSIC\subject-info_def.csv